### ISSUE TITLE
Options de compilation dans un fichier Markdown

### ISSUE THREAD

**Issue by flodavid** [ShihoWasTaken/ezlanguage#11]
Le fichier "Ajoutspossiblespourlesoptionsdecompilation.odt" n'est pas visible depuis github, c'est dommage, car il est très simple et serait compatible markdown

**Comment by flodavid** [comment]
C'est fait ? @alefol

**Comment by alefol** [comment]
Le Fichier  "Ajoutspossiblespourlesoptionsdecompilation.odt"  était une ébauche, le fichier contenant les options du compilateur valides se trouve dans la branche documents.  Par contre il est n'est pas sous format markdown, j'ai donc créé un autre fichier "options_compilateur" à partir de github. @flodavid

**Comment by flodavid** [comment]
C'était pour les propositions, pour qu'on puisse les voir et en ajouter depuis GitHub. Les options sont peut être finalisées, donc c'est peut être pas utile.
Par contre, tu aurais du le mettre dans le dossier architecture, le dossier doc/ c'est pour ... la doc (du code)
